spring.application.name: customer-service-grpc
spring.output.ansi.enabled: always

management.endpoints.web.exposure.include: metrics
management.endpoint.metrics.enabled: true

server.port: 8081
grpc.server.port: 9081

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/